### ISSUE TITLE
[FEAT] custom columns order

### ISSUE THREAD

**Issue by Equationzhao** [Equationzhao/g#91]
## feature
the custom column order can bring more flexibility to daily use.

## solution
the order can be defined in the config file or be passed by the command line option

eg:
through config
```yaml
Args:
  - hyperlink=never
  - icons
  - no-update

Order:
  - Permissions 
  - Size     
  - Owner        
  - Group 
  - Time Modified   
  - Name
```
or `g --order='Permissions,Size,Owner,Group,Time Modified,Name' --long`
